UPDATE vocabulary SET example='The fire destroyed the building.', example_translation='大火烧毁了这座建筑。' WHERE word='destroy' AND example='This is useful for study.';
UPDATE vocabulary SET example='The room was in a state of disorder.', example_translation='房间里一片混乱。' WHERE word='disorder' AND example='This is useful for study.';
UPDATE vocabulary SET example='The shop window displays the latest fashions.', example_translation='商店橱窗展示了最新的时装。' WHERE word='display' AND example='This is useful for study.';
UPDATE vocabulary SET example='His answer displeased me.', example_translation='他的回答让我不高兴。' WHERE word='displease' AND example='This is useful for study.';
UPDATE vocabulary SET example='We have a lot of waste for disposal.', example_translation='我们要处理很多垃圾。' WHERE word='disposal' AND example='This is useful for study.';
UPDATE vocabulary SET example='How should I dispose of this old computer?', example_translation='我该如何处理这台旧电脑？' WHERE word='dispose' AND example='This is useful for study.';
UPDATE vocabulary SET example='They are in dispute over the contract.', example_translation='他们就合同问题发生了争执。' WHERE word='dispute' AND example='This is useful for study.';
UPDATE vocabulary SET example='The service dissatisfied the customers.', example_translation='这项服务让顾客不满意。' WHERE word='dissatisfy' AND example='This is useful for study.';
UPDATE vocabulary SET example='Sugar dissolves in water.', example_translation='糖溶于水。' WHERE word='dissolve' AND example='This is useful for study.';
UPDATE vocabulary SET example='We heard a distant roll of thunder.', example_translation='我们听到了远处的雷声。' WHERE word='distant' AND example='This is useful for study.';
UPDATE vocabulary SET example='There is a distinct smell of gas.', example_translation='有一股明显的气味。' WHERE word='distinct' AND example='This is useful for study.';
UPDATE vocabulary SET example='It is important to make a distinction between the two.', example_translation='区分这两者很重要。' WHERE word='distinction' AND example='This is useful for study.';
UPDATE vocabulary SET example='The news caused her great distress.', example_translation='这个消息让她非常痛苦。' WHERE word='distress' AND example='This is useful for study.';
UPDATE vocabulary SET example='We need to distribute the leaflets.', example_translation='我们需要分发传单。' WHERE word='distribute' AND example='This is useful for study.';
UPDATE vocabulary SET example='The distribution of wealth is uneven.', example_translation='财富分配不均。' WHERE word='distribution' AND example='This is useful for study.';
UPDATE vocabulary SET example='She lives in the business district.', example_translation='她住在商业区。' WHERE word='district' AND example='This is useful for study.';
UPDATE vocabulary SET example='Please do not disturb the baby.', example_translation='请不要打扰婴儿。' WHERE word='disturb' AND example='This is useful for study.';
UPDATE vocabulary SET example='The car slid into a ditch.', example_translation='汽车滑进了沟里。' WHERE word='ditch' AND example='This is useful for study.';
UPDATE vocabulary SET example='He dove into the pool.', example_translation='他跳进了游泳池。' WHERE word='dive' AND example='This is useful for study.';
UPDATE vocabulary SET example='The city has a diverse population.', example_translation='这个城市的人口具有多样性。' WHERE word='diverse' AND example='This is useful for study.';
UPDATE vocabulary SET example='The river divides the city.', example_translation='这条河将城市一分为二。' WHERE word='divide' AND example='This is useful for study.';
UPDATE vocabulary SET example='The division of labor is efficient.', example_translation='分工是有效率的。' WHERE word='division' AND example='This is useful for study.';
UPDATE vocabulary SET example='They decided to divorce.', example_translation='他们决定离婚。' WHERE word='divorce' AND example='This is useful for study.';
UPDATE vocabulary SET example='What do you want to do?', example_translation='你想做什么？' WHERE word='do' AND example='This is useful for study.';
UPDATE vocabulary SET example='The ship is at the dock.', example_translation='船在码头。' WHERE word='dock' AND example='This is useful for study.';
UPDATE vocabulary SET example='The dog is barking.', example_translation='狗在叫。' WHERE word='dog' AND example='This is useful for study.';
UPDATE vocabulary SET example='It costs one dollar.', example_translation='它花了一美元。' WHERE word='dollar' AND example='This is useful for study.';
UPDATE vocabulary SET example='Domestic flights are cheaper.', example_translation='国内航班更便宜。' WHERE word='domestic' AND example='This is useful for study.';
UPDATE vocabulary SET example='Donkeys are stubborn animals.', example_translation='驴是顽固的动物。' WHERE word='donkey' AND example='This is useful for study.';
UPDATE vocabulary SET example='Please close the door.', example_translation='请关门。' WHERE word='door' AND example='This is useful for study.';
UPDATE vocabulary SET example='I live in the dorm.', example_translation='我住在宿舍。' WHERE word='dorm' AND example='This is useful for study.';
UPDATE vocabulary SET example='The dormitory is quiet.', example_translation='宿舍很安静。' WHERE word='dormitory' AND example='This is useful for study.';
