-- 用户操作日志表
CREATE TABLE IF NOT EXISTS `user_log` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT(20) NOT NULL COMMENT '用户ID',
    `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    `module` VARCHAR(50) NULL DEFAULT NULL COMMENT '操作模块 (reading, listening, speaking, writing, exam)',
    `action` VARCHAR(50) NULL DEFAULT NULL COMMENT '操作类型 (login, logout, submit, view, share)',
    `details` VARCHAR(500) NULL DEFAULT NULL COMMENT '操作详情/描述',
    `ip` VARCHAR(50) NULL DEFAULT NULL COMMENT '请求IP地址',
    `ip_country` VARCHAR(50) NULL DEFAULT NULL COMMENT 'IP所属国家',
    `ip_province` VARCHAR(50) NULL DEFAULT NULL COMMENT 'IP所属省份',
    `ip_city` VARCHAR(50) NULL DEFAULT NULL COMMENT 'IP所属城市',
    `browser` VARCHAR(50) NULL DEFAULT NULL COMMENT '浏览器类型',
    `os` VARCHAR(50) NULL DEFAULT NULL COMMENT '操作系统',
    `device_type` VARCHAR(20) NULL DEFAULT NULL COMMENT '设备类型 (Desktop, Mobile, Tablet)',
    `request_url` VARCHAR(255) NULL DEFAULT NULL COMMENT '请求URL',
    `request_method` VARCHAR(10) NULL DEFAULT NULL COMMENT '请求方法 (GET, POST, PUT, DELETE)',
    `status` TINYINT(1) NULL DEFAULT 1 COMMENT '操作状态 (0:失败, 1:成功)',
    `error_msg` VARCHAR(500) NULL DEFAULT NULL COMMENT '错误信息',
    `duration` BIGINT(20) NULL DEFAULT NULL COMMENT '操作耗时(毫秒)',
    `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_username` (`username`),
    INDEX `idx_module` (`module`),
    INDEX `idx_action` (`action`),
    INDEX `idx_ip` (`ip`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户操作日志表';
