<script setup>
import { computed } from 'vue'
import { NAlert, NCard, NModal, NSpin } from 'naive-ui'
import { Sparkles } from 'lucide-vue-next'

const props = defineProps({
  show: {
    type: Boolean,
    default: false
  },
  loading: {
    type: Boolean,
    default: false
  },
  briefingData: {
    type: Object,
    default: () => ({
      title: '',
      summary: '',
      alert: ''
    })
  }
})

const emit = defineEmits(['update:show'])

const generatedAt = computed(() => new Date().toLocaleString('zh-CN'))
</script>

<template>
  <n-modal :show="show" @update:show="emit('update:show', $event)">
    <n-card
      style="width: 600px; max-width: 90vw"
      :bordered="false"
      size="huge"
      role="dialog"
      aria-modal="true"
      class="glass-modal"
    >
      <template #header>
        <div class="flex items-center gap-2 text-indigo-400">
          <Sparkles :size="24" />
          <span class="font-bold text-xl">{{ briefingData.title || 'AI 每日运营简报' }}</span>
        </div>
      </template>

      <div v-if="loading" class="py-12 flex flex-col items-center justify-center">
        <n-spin size="large" />
        <p class="mt-4 text-zinc-400 animate-pulse">正在分析昨日运营数据...</p>
      </div>

      <div v-else class="briefing-content">
        <n-alert v-if="briefingData.alert" type="error" title="风险预警" class="mb-6">
          {{ briefingData.alert }}
        </n-alert>

        <div class="whitespace-pre-line text-base leading-relaxed text-zinc-200">
          {{ briefingData.summary }}
        </div>

        <div class="briefing-footer mt-8 pt-6 border-t border-white/10 text-xs text-zinc-500 flex justify-between">
          <span>Generated by LearnSphere AI Analysis Engine</span>
          <span>{{ generatedAt }}</span>
        </div>
      </div>
    </n-card>
  </n-modal>
</template>

<style scoped>
.glass-modal {
  background: rgba(9, 9, 11, 0.94);
  backdrop-filter: blur(18px);
  border: 1px solid rgba(255, 255, 255, 0.08);
  box-shadow: 0 24px 80px rgba(0, 0, 0, 0.45);
}

.briefing-content {
  color: #e4e4e7;
}

.briefing-footer {
  letter-spacing: 0.01em;
}
</style>
